# Generated by Django 5.1.6 on 2025-02-19 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='full_text',
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(default=30, verbose_name='Время приготовления (мин)'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default='Описание отсутствует', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(default='Ингредиенты отсутствуют', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='steps',
            field=models.TextField(default='Шаги приготовления отсутствуют', verbose_name='Шаги приготовления'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
